#include <avr/interrupt.h>

/* Extern Request Handler */
void Change_PowerMode(char c);

/* Initialize Wakeup Pin */
void wakeup_init(void);

/* Interrupt Request generated by RTC */
ISR(PCINT1_vect);

/* This routine is needed for a proper soft reset* 
* look @ https://www.nongnu.org/avr-libc/user-manual/FAQ.html#faq_softreset for further information */
void wdt_init(void) __attribute__((naked)) __attribute__((section(".init3")));

